name: CI/CD

on:  
  push:
    tags:
      - 'v**'

env:
  VERSION: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag version
        id: get_version
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
          echo "VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t farhan15r/ci-cd-test:$VERSION .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: docker push farhan15r/ci-cd-test:$VERSION
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Update Docker Compose via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          VERSION: ${{ needs.build.outputs.VERSION }
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: VERSION
          script: |
            echo $VERSION
            cd /app
            sed -i "s/image: farhan15r\/ci-cd-test:.*/image: farhan15r\/ci-cd-test:$VERSION/g" compose.yml
            cat compose.yml