name: CI/CD

on:  
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t farhan15r/ci-cd-test:$VERSION .
      
      - name: Login Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin