name: Build and Push Image

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set version from tag
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         VERSION=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)
         echo "Versi dari tag: $VERSION"
         evho "${GITHUB_REF}"
