name: CI/CD

on:  
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag version
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)
          ${{ vars.set('VERSION', VERSION) }}

      - name: Build and push Docker image
        run: |
          docker build -t my-docker-image:${{ vars.VERSION }} .