name: CI/CD

on:  
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t my-docker-image:$VERSION .